FROM node:22-slim AS builder

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app


COPY package.json pnpm-lock.yaml ./

COPY . .

RUN pnpm run build

RUN rm -rf node_modules && pnpm install --prod --frozen-lockfile

FROM node:22-slim AS runner

RUN apt-get update && apt-get install -y \
    ffmpeg \
    python3 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

ENV NODE_ENV=production
ENV NODE_OPTIONS="--no-warnings"

USER node

CMD ["node", "dist/index.js"]
